### ISSUE TITLE
Running on Linux?

### ISSUE THREAD

**Issue by chiehmin** [Mpmart08/MusicPlayer#22]
Hi, I am really interested in your project. However I am a linux user and it seems like it does not support Linux platform. What is the problem that stops it from running on linux?

**Comment by Mpmart08** [comment]
We just haven't done any testing on Linux. This was developed on Windows, and it didn't take much effort to get it working on Mac, so I'm sure we could get it to work on Linux. I have a virtual machine setup with Ubuntu so I can do some testing.

**Comment by chiehmin** [comment]
I tried running the jar, but it stuck at this screen after import music library.

![screenshot from 2016-07-02 13-16-39](https://cloud.githubusercontent.com/assets/1941281/16538451/65c6f594-3fea-11e6-87b2-904aca21970e.png)

**Comment by chiehmin** [comment]
Here's the error log.

```
Exception in thread "Thread-5" MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:511)
	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:414)
	at app.musicplayer.MusicPlayer.lambda$start$6(MusicPlayer.java:155)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:274)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:467)
	... 3 more

```

**Comment by GerardoPrada** [comment]
Thanks for the link. So it seems that JavaFX does not support the latest version of Ubuntu. Since there's nothing we can do about this, I'm closing the issue.

**Comment by chiehmin** [comment]
I think you can try to pack the dependent libraries with MusicPlay using [snap](http://snapcraft.io/)
